### ISSUE TITLE
tiles.wmflabs.org für Kartenansicht wird nicht mehr unterstützt

### ISSUE THREAD

**Issue by Roadrunner89** [Retschga/FWmonitor#11]
Der genannte Dienst wurde eingestellt, was zu einer nicht mehr funktionierenden Kartenansicht führt. 
In der Version 2.4 konnte ich das Problem durch auskommentieren des Layers beheben

VG
Alex

**Comment by Retschga** [comment]
Ich habe eine neue Version 2.4.1 erstellt, in der ich die wmflabs tilelayer entfernt habe.

VG
Johannes

**Comment by Roadrunner89** [comment]
Danke für die schnelle Antwort. 

Das Problem sollte aber auch die Version 3 betreffen, oder ? 
Zumindest ist es mir auf dem Testsystem aufgefallen, ich habe es dort aber noch nicht gefixed

**Comment by Retschga** [comment]
Ja das besteht auch in Version 3, da habe ich aber letztens die URLs über die .env anpassbar gemacht, so kann mann sie einfach rausnehmen oder ändern.

**Comment by Roadrunner89** [comment]
Perfekt, danke :)
