### ISSUE TITLE
Alarm E-Mail Eingang

### ISSUE THREAD

**Issue by meinsm** [Retschga/FWmonitor#4]
Hallo,
das Projekt ist super.
Ist es geplant, das ganze auch mit Mails anstelle von Fax zu machen?

**Comment by Retschga** [comment]
Hallo,
bei uns gibt es leider keine Alarm E-Mails. Es wäre aber mit einer Beispielmail relativ leicht eingebaut.

**Comment by Retschga** [comment]
Email Alarmeingang ist jetzt eingebaut (Testversion)
